[package]
name = "mattschrubb/fusion"
description = "Fusion version 0.2.0"
version = "0.2.0-temp"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

include = ["src, wally.toml, wally.lock"]
#exclude = ["**"]

[dependencies]
