[package]
name = "mattschrubb/fusion"
description = "Fusion version 0.2.0"
version = "0.2.0-beta"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

include = ["src, wally.toml"]
exclude = ["**"]

[dependencies]
